version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      SECURITY_USER: "my_username"
      SECURITY_PASS: "my_password"
      SECURITY_ENABLED: 0
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/projects
      #- ${PWD}/allure-results:/app/allure-results
      #- ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
