name: test-harness-verity-dotnet
# RUNSET_NAME: "Verity to DotNet"
# Scope: Connections RFC0160
# Exceptions: None
# SKIP
#
# Currently skipped due to issues with the tests being
#     canceled intermittently due to (seemingly)
#     resource issues.
#
# Summary
#
# This runset uses the current main branch of DotNet for all of the agents except Acme (Issuer),
# which uses the dev branch of Evernym Verity. The runset covers all of the AIP 1.0 tests
# under the connection protocol RFC0160.
#
# Current
#
# Initial implementation to get the tests running smoothly. Currently testing connection only.
#
# *Status Note Updated: 2021.09.23*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://dev.bcovrin.vonx.io"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a dotnet -a verity"
          TEST_AGENTS: "-d dotnet -a verity"
          TEST_SCOPE: "-t @RFC0160 -t @AcceptanceTest -t ~@wip -t ~@AIP20"
          REPORT_PROJECT: dotnet-a-verity
      #   continue-on-error: true
      # - name: run-send-gen-test-results-secure
      #   uses: ./test-harness/actions/run-send-gen-test-results-secure
      #   with:
      #     REPORT_PROJECT: dotnet-a-verity
      #     ADMIN_USER: ${{ secrets.AllureAdminUser }}
      #     ADMIN_PW: ${{ secrets.AllureAdminPW }}
