name: test-harness-afgo-acapy
# RUNSET_NAME: "AF-Go to ACA-PY"
# Scope: pre-AIP 2.0
# Exceptions: None
# 
# Summary
#
# This runset uses the current master branch of Aries Framework Go for all of the agents except Bob (holder),
# which uses the  main branch of ACA-Py . The runset cover several AIP 2.0 tests
# using RFC0023 (DID Exchange).
#
# Current
# 
# All of the tests being executed in this runset are passing.
#
# *Status Note Updated: 2021.09.27*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "40 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-orb
        uses: ./test-harness/actions/service-command
        with:
          SERVICE_COMMAND: "start orb"
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a afgo-interop -a acapy-main"
          TEST_AGENTS: "-d afgo-interop -b acapy-main"
          OTHER_PARAMS: "-v 20"
          TEST_SCOPE: "-t @RFC0023,@RFC0453,@RFC0454 -t ~@wip -t ~@CredFormat_Indy"
          REPORT_PROJECT: afgo-b-acapy
        env:
          EMIT-NEW-DIDCOMM-PREFIX: true
          EMIT-NEW-DIDCOMM-MIME-TYPE: true
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: afgo-b-acapy 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
