name: test-harness-javascript-findy
# RUNSET_NAME: "AFJ to findy"
# Scope: AIP 1.0
# Exceptions: Revocation
#
# Summary
#
# This runset uses the latest release of Aries Framework Javascript for all of the agents except Bob (holder),
# which uses the current main branch of findy-agent. The runset covers all of the AIP 1.0 tests that
# are known to work with findy as the holder. Excluded are those tests that involve Revocation.
#
# Current
#
# All of the tests being executed in this runset are failing. There is an issue with afj sending the connection
# response, and throws an error processing inbound message.
#
# *Status Note Updated: 2021.09.28*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a javascript -a findy"
          TEST_AGENTS: "-d javascript -b findy"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10 -t ~@wip -t ~@revocation -t ~@RFC0025"
          REPORT_PROJECT: javascript-b-findy
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: javascript-b-findy
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
