name: test-harness-javascript-javascript
# RUNSET_NAME: "AFJ to AFJ"
# Scope: AIP 1.0
# Exceptions: Revocation
#
# Summary
#
# This runset uses the current main branch of Aries Framework - JavaScript for all of the agents. The runset runs all of the tests in the suite
# that are expected to pass given the current state of the framework's support for AIP 1. Tests related to revocation (Indy HIPE 0011) are not included.
#
# Current
# 
# All of the tests being executed in this runset are passing.
# 
# *Status Note Updated: 2021.03.05*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a javascript"
          TEST_AGENTS: "-d javascript"
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t ~@revocation -t ~@RFC0023 -t ~@DIDExchangeConnection"
          REPORT_PROJECT: javascript
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: javascript
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
