name: test-harness-ariesvcx-ariesvcx
# RUNSET_NAME: "aries-vcx to aries-vcx"
# Scope: AIP 1.0
# Exceptions: Proof Proposals, Public Dids, Revocations
#
# Current
# 
# Passing tests: @T003-RFC0036 @T001-RFC0160 @T002-RFC0160 @T003-RFC0160 @T001-RFC0037
# 
# End
  # on:
  #   workflow_dispatch:
  #   schedule:
  #     - cron: "35 0 * * *"
on:
  push:
    branches:
      - "**"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a aries-vcx"
          TEST_AGENTS: "-d aries-vcx"
          TEST_SCOPE: "-t ~@T001-RFC0036 -t ~@T001.1-RFC0036 -t ~@T002-RFC0036 -t ~@T004-RFC0036 -t ~@T005-RFC0036 -t ~@T006-RFC0036 -t ~@T001.1-RFC0037 -t ~@T001.2-RFC0037 -t ~@T001.3-RFC0037 -t ~@T001.4-RFC0037 -t ~@T001.5-RFC0037 -t ~@T002-RFC0037 -t ~@T003-RFC0037 -t ~@T003.1-RFC0037 -t ~@T004-RFC0037 -t ~@T005-RFC0037 -t ~@T006-RFC0037 -t ~@T004-RFC0160 -t ~@T005-RFC0160 -t ~@T006-RFC0160 -t ~@T007-RFC0160 -t ~@RFC0023 -t ~@revocation -t ~@RFC0453 -t ~@RFC0454"
          REPORT_PROJECT: aries-vcx  
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: agent-logs
          path: ./logs
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: aries-vcx 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
