name: test-harness-acapy-dotnet
# RUNSET_NAME: "ACA-PY to AF-Go"
# Scope: AIP 2.0 RFC0023 Only
# 
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Aries Framework Go. The runset cover several AIP 2.0 tests
# using RFC0023 (DID Exchange).
#
# Current
# 
# None of the tests are currently working and issues have been created to try to determine three identified issues.
# One might be in the test suite, while two others appear to be in the Aries Framework Go.
# 
# *Updated: 2021.03.05*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          DEFAULT_AGENT: acapy-main
          BOB_AGENT: afgo-master
          TEST_SCOPE: "-t @RFC0023 -t ~@wip -t ~@T003-RFC0023 -t ~@T004-RFC0023"
          REPORT_PROJECT: acapy-b-afgo
        env:
          EMIT-NEW-DIDCOMM-PREFIX: true
          EMIT-NEW-DIDCOMM-MIME-TYPE: true
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-afgo 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
