name: test-harness-acapy-afgo
# RUNSET_NAME: "ACA-PY to AF-Go"
# Scope: pre-AIP 2.0
# Exceptions: None
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Aries Framework Go. The runset cover several AIP 2.0 tests
# using RFC0023 (DID Exchange).
#
# Current
#
# All of the tests being executed in this runset are passing.
#
# *Status Note Updated: 2021.09.27*
#
# End
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-orb
        uses: ./test-harness/actions/service-command
        with:
          SERVICE_COMMAND: "start orb"
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main -a afgo-interop"
          TEST_AGENTS: "-d acapy-main -b afgo-interop"
          OTHER_PARAMS: "-v 20"
          TEST_SCOPE: "-t @RFC0023,@RFC0453,@RFC0454,@RFC0025 -t ~@wip -t ~@CredFormat_Indy -t ~@Transport_NoHttpOutbound -t ~@Transport_Ws -t ~@RFC0160 -t ~@RFC0434 -t ~@DidMethod_orb"
          REPORT_PROJECT: acapy-b-afgo
        env:
          EMIT_NEW_DIDCOMM_PREFIX: true
          EMIT_NEW_DIDCOMM_MIME_TYPE: true
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        if: ((github.event_name != 'pull_request' && github.repository == 'hyperledger/aries-agent-test-harness'))
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-afgo
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
