name: test-harness-dotnet-dotnet
# RUNSET_NAME: "AF-.NET to AF-.NET"
# Scope: AIP 1.0 except revocation and proof proposals
# 
# Summary
#
# This runset uses the current main branch of Aries Framework .NET for all of the agents. The runset runs all of the tests in the suite
# that are expected to pass given the current state of Aries Framework .NET's support for AIP 1. Tests related to revocation (Indy HIPE 0011)
# and holders initiating present proof protocols using a "proposal" message are not included.
#
# Current
# 
# All of the tests being executed in this runset are passing.
# 
# *Updated: 2021.03.05*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness
        with:
          DEFAULT_AGENT: dotnet-master
          BOB_AGENT: dotnet-master
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t ~@RFC0011 -t ~@ProofProposal -t ~@RFC0023"
          REPORT_PROJECT: dotnet
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: dotnet 
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
