name: test-harness-acapy-javascript
# RUNSET_NAME: "ACA-PY to AF-JS"
# Scope: AIP 1.0 except revocation
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Aries Framework JavaScript. The runset covers all of the AIP 1.0 tests
# except those that are known **not** to work with the Aries Framework JavaScript as the holder,
# notably those that involve revocation.
#
# Current
# 
# Only about half of the tests are currently running. The issues seem to be related to the set of tags
# of the test cases being run as a number of the revocation tests are running and shouldn't be. As well,
# the tests with the holder proposing a proof are not running, as that feature is not supported in AFJ.
# 
# *Updated: 2021.03.05*
#
# End
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'schedule' && github.repository == 'hyperledger/aries-agent-test-harness') || (github.event_name != 'schedule')
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v2
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          DEFAULT_AGENT: acapy-main
          BOB_AGENT: javascript
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t ~@RFC0011 -t ~@RFC0023 -t ~@DIDExchangeConnection"
          REPORT_PROJECT: acapy-b-javascript
        continue-on-error: true
      - name: run-send-gen-test-results-secure
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-javascript
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
